version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - "server"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
